networks:
  redpanda_network:
    driver: bridge
    ipam:
      config:
      - subnet: "172.24.1.0/24"
        gateway: "172.24.1.1"
services:
  redpanda_source:
    image: docker.vectorized.io/vectorized/redpanda:v22.3.11
    container_name: redpanda_source
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://172.24.1.10:19092
      - --advertise-kafka-addr
      - internal://172.24.1.10:9092,external://127.0.0.1:19092
      