apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-configmap
  namespace: redpanda
  labels:
    app: redpanda-edge
data:
  agent.yaml: |
    create_topics: true
    source:
      name: "source"
      boots