apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-configmap
  namespace: redpanda
  labels:
    app: redpanda-edge
data:
  agent.yaml: |
    create_topics: true
    source:
      name: "source"
      bootstrap_servers: redpanda-src:10092 # use secured internal interface
      # List of outbound topics to push from sou